namePrefix: kustomize-
resources:
- ../base/guestbook-ui-deployment.yaml
- ../base/guestbook-ui-svc.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: guestbook-ui
  newName: 198409097547.dkr.ecr.us-east-1.amazonaws.com/test/guestbook # {"$imagepolicy": "flux-system:prod-image-policy:name"}
  newTag: prod-xds13423xd-202204245933 # {"$imagepolicy": "flux-system:prod-image-policy:tag"}
