namePrefix: kustomize-

resources:
- guestbook-ui-deployment.yaml
- guestbook-ui-svc.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: 198409097547.dkr.ecr.us-east-1.amazonaws.com/test
  newName: 198409097547.dkr.ecr.us-east-1.amazonaws.com/test # {"$imagepolicy": "flux-system:image-policy:name"}
  newTag: dev-k3y0u5f2-202104211603 # {"$imagepolicy": "flux-system:image-policy:tag"}
