namePrefix: kustomize-
resources:
- guestbook-ui-deployment.yaml
- guestbook-ui-svc.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: guestbook-ui
  newName: 198409097547.dkr.ecr.us-east-1.amazonaws.com/test # {"$imagepolicy": "flux-system:image-policy:name"}
  newTag: dev-xfs1fex0-209903021102 # {"$imagepolicy": "flux-system:image-policy:tag"}
