---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: prod-demo
  namespace: flux-system
spec:
  interval: 5m0s
  targetNamespace: prod
  path: ./kustomize-guestbook/prod/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m
