---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: dev-demo
  namespace: flux-system
spec:
  interval: 5m0s
  targetNamespace: dev
  path: ./kustomize-guestbook/dev/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m
