name: Python

on:
  push:
    branches: [ master ]
    paths:
      - 'python/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: System information
        shell: bash
        run: |
          df -h && ps aux && netstat -tlnp && lscpu && free -g

      - name: Install python dependences
        shell: bash
        run: |
          pip3 install --user boto3 "moto[all]" yapf shfmt-py mysql-connector pymysql six PyHamcrest requests environs fire

      - name: Run command
        shell: bash
        run: |
          python3 -c "from hamcrest import assert_that, is_, none, is_not"

      - name: Python version
        shell: bash
        run: |
          python3 --version
